[package]
name = "discord_bot_rustc"
version = "0.1.0"
authors = ["Lin2D2 <linus@thebehrens.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
